[package]
name = "raycast"
version = "0.1.0"
authors = ["Charlie Thomson <charliecthomson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.20.0-alpha4"
piston = "0.49.0"
pistoncore-winit_window = "0.12.0"
pistoncore-window = "0.44.0"